name: calander
base: core18
version: '0.1.0'
summary: Calander for terminal
description: |
  View colorful calander from the terminal.

grade: devel
confinement: devmode

parts:
  calander:
    plugin: rust
    source: https://github.com/youaremagic/calander.git

apps:
  calander:
    command: bin/calander
