name: calander
base: core18
version: '0.2.0'
summary: Calander for terminal
description: |
  View colorful calander from the terminal.

grade: stable
confinement: strict
contact: magicisyou@outlook.com
license: MIT
source-code: https://github.com/youaremagic/calander

parts:
  calander:
    plugin: rust
    source: https://github.com/youaremagic/calander.git

apps:
  calander:
    command: bin/calander
